### ISSUE TITLE
Build fails on latest rustc nightly

### ISSUE THREAD

**Issue by zslayton** [carllerche/mio#152]
This has the same root cause as carllerche/nix-rust#103. I tried changing the offending lifetime in `nix-rust` to `'static` in my environment just to get working again and a similar problem cropped up in `mio`:

```
   Compiling mio v0.3.2 (https://github.com/carllerche/mio#c66d1cec)
/home/zslayton/.cargo/git/checkouts/mio-8730c946209c11b6/master/src/util/slab.rs:270:10: 270:12 error: the lifetime parameter `'b` is not constrained by the impl trait, self type, or predicates [E0207]
/home/zslayton/.cargo/git/checkouts/mio-8730c946209c11b6/master/src/util/slab.rs:270 impl<'a, 'b, T> Iterator for SlabMutIter<'a, T> {
                                                                                              ^~
error: aborting due to previous error
Could not compile `mio`.

```

**Comment by fhartwig** [comment]
In this case, the compiler found an actual problem, as the current lifetimes are really unsafe (I've just managed to get a `&'static` reference out of `SlabMutIter`, which clearly shouldn't be possible).

If you want mio to build, you can get a working version from my repo at https://github.com/fhartwig/mio/tree/rustup (or you could just remove the slab iterator stuff if you're not using it). I'm not making a pull request yet because a proper fix will involve bumping the `nix` version bound (and I haven't gotten around to fixing the tests yet).

**Comment by carllerche** [comment]
This should be fixed on master.
