### ISSUE TITLE
Allow selecting on which interface to join/leave multicast groups

### ISSUE THREAD

**Issue by sdroege** [carllerche/mio#187]
I see that nix already has the required struct definitions to set the interfaces, but it's currently not used or exposed in the API.

I would propose to add a Option<String> parameter to the join/leave functions, which can take an interface name. This string could then be converted to a interface index with if_nametoindex().

Reason for exposing this as a string is that it's more convenient to use by applications than an interface index directly.

(Note about Windows portability: you can implement if_nametoindex() there with GetAdaptersAddresses())

**Comment by sdroege** [comment]
I could also prepare a patch for this if this is something you'd like to have

**Comment by rrichardson** [comment]
how do you envision the interfaces exactly for mio/nix?

**Comment by rrichardson** [comment]
Answering my last question, it looks like posix/bsd. also there is https://msdn.microsoft.com/en-us/library/windows/desktop/bb408409%28v=vs.85%29.aspx

**Comment by sdroege** [comment]
if_nametoindex is BSD and POSIX 2001.

Interface in mio: join_multicast(&self, multi: &IpAddr, iface: &Option<String>)

iface can be None (what we do now) or Some("eth0") for example. Same for leave_multicast()

**Comment by rrichardson** [comment]
I gotcha, so this is for cases where you need to disambiguate interfaces for a given ip addr?

**Comment by rrichardson** [comment]
Also, the reason why I recommend the additional function is that I am reluctant to change the existing interface because existing code does use it :)

**Comment by rrichardson** [comment]
Ok. Looking more deeply at the code. I am for your proposed interface, but am also for keeping the interface as-is and adding a new fn.  I'll defer to @carllerche

**Comment by carllerche** [comment]
So far, I have just mirrored the APIs provided by Rust: https://doc.rust-lang.org/stable/std/net/struct.UdpSocket.html

Ideally, the requested feature would also be provided by `std::net::UnixSocket` as well...

Regarding breaking current APIs, obviously it should be done with caution, but 0.4 is going to be a breaking change. I'm just unsure how to go about this since Rust will most likely introduce a different API from whatever we do here...

**Comment by sdroege** [comment]
@rrichardson The reason is that it's apparently not portable to not set any interface at all if there are multiple. You might join on all interfaces, maybe only on a "default" one, or on none at all and instead get an error (the latter happens on Android).

Regarding if_nametoindex(), it's only available on newer Windows versions. On older versions you can easily reimplement it based on other Windows APIs, I wrote some code for GLib for that some years ago.



For changing the API or adding a new set of functions, that's for you to decide. I think it would be nicer to change the API now that mio is still young instead of cluttering the API with lots of very similar functions.

FWIW, GLib has 3 parameters for joining/leaving multicast groups: the multicast group, the interface name and a boolean to select source specific multicast (see Wikipedia).

**Comment by carllerche** [comment]
Thanks for submitting the issue.

I'm going to close this due to inactivity. The state / direction of Mio has changed significantly. Mio has a goal of providing Tcp / Udp APIs equivalent to Rust's STD. Mio also has made it possible to implement custom `Evented` types, so it should be possible to implement extra features in third party libraries.
