### ISSUE TITLE
TcpSocket should provide a method for getting the error after `connect`

### ISSUE THREAD

**Issue by zonyitoo** [carllerche/mio#197]
If `TcpSocket::connect` returns with `(_, false)`, we will register it into event loop with `Interest::writable()`. When notified by event loop, in C, we may need to call

```c
if (getsockopt(fd, SOL_SOCKET, SO_ERROR, &result, &result_len) < 0) {
    // error, fail somehow, close socket
    return;
}

// error code is in result
```

to check if connection is succeeded.

**Comment by chaaz** [comment]
I'm interested in this, too. For now, I'm explicitly calling `stream.take_socket_error()` on the registered stream as the first thing to do when notified, which seems a reasonable workaround.

**Comment by zonyitoo** [comment]
Yes, I have added `take_socket_error` for workaround. I don't know if there is another better solution for this.

**Comment by carllerche** [comment]
How does it work portability wise? This seems good though. I would bring in @alexcrichton for specific API ideas. Maybe `take_last_error`?

**Comment by alexcrichton** [comment]
Ah yeah, net2 calls this [`take_error`](http://doc.rust-lang.org/net2-rs/net2/trait.TcpStreamExt.html#tymethod.take_error)

**Comment by carllerche** [comment]
I would go with `take_error` then :)

**Comment by carllerche** [comment]
Thanks for submitting the issue.

I'm going to close this due to inactivity. The state / direction of Mio has changed significantly. This issue may or may not be resolved.

For context, Mio has a goal of providing Tcp / Udp APIs equivalent to Rust's STD. Mio also has made it possible to implement custom `Evented` types, so it should be possible to implement extra features in third party libraries.
