### ISSUE TITLE
Cannot register a custom Fd with the event loop

### ISSUE THREAD

**Issue by diwic** [carllerche/mio#226]
It seems either impossible or undesired to register a custom Fd with the event loop, because `Evented` and `Io` names are hidden/private.
 
In my case, I got an eventfd from nix and now I want to wait for it to become readable. Am I missing something?

**Comment by diwic** [comment]
I'd add that I prefer not to put my fd in an `Io` struct if possible, because I'm not sure I'd like it to close when the Io goes out of scope.

**Comment by tomjakubowski** [comment]
> I'd add that I prefer not to put my fd in an Io struct if possible, because I'm not sure I'd like it to close when the Io goes out of scope.

Can you dup eventfds? That might be an option (pass the duped eventfd into the Io struct and hold onto your other one for whatever purpose).

**Comment by diwic** [comment]
I believe I could dup the eventfds, but it would double the amount of open eventfds, and I might have many of them, and don't want to hit the "max fds per process" limit.

Also, the fact that `Io` is hidden from the docs seems to indicate either that it is unstable, and/or you don't want people to use the `Io` struct directly...?

**Comment by carllerche** [comment]
This is definitely an issue. I think this ability was lost in the refactor from v0.3 -> v0.4. A bunch of Mio concepts were made hidden as they are not portable w/ windows.

I'm thinking that the best way to handle this right now would be to have something like `mio::unix::EventedFd<T: std::os::unix::io::AsRawFd>` that implements `Evented`. Thoughts?

**Comment by carllerche** [comment]
However, I believe that the story will improve with specialization. When specialization (rust-lang/rfcs#1210) is available, I believe that mio can just implemented `Evented` for `T: AsRawFd`.

**Comment by diwic** [comment]
Thanks for looking into it. Short term, can't you just have `RawFd` implement `Evented`?

Long term, it would be nice to be able to have your own structs implement `Evented` as well. E g, if you have your own IPC (that contains three sockets and two file descriptors, or something) that would enable the user of that IPC to simple register the IPC object with the event loop.

**Comment by diwic** [comment]
JFTR - eventfds are not the only fds I want to use. Both D-Bus and ALSA apis also give you fds that you can poll for.

**Comment by carllerche** [comment]
Sorry for the delay. Yes, I think it makes sense to implement `Evented` on `RawFd`. I would take a PR for this.

**Comment by carllerche** [comment]
So, @alexcrichton has correctly pointed out that `RawFd` is just an alias for `i32`. The danger being that now, on windows (when it happens), `i32` will also implemented `Evented`.

I am wondering if a better strategy would be to add a `mio::unix::EventLoopExt` trait that adds `register_raw` that takes the same arguments as `register_opt`, the only difference being instead of accepting a `T: Evented` it takes a `RawFd` directly. This would explicitly only expose the raw fd registering to unix platforms following the Rust's std pattern for platform specific extensions.

**Comment by diwic** [comment]
Yeah, IMO, `RawFd` should have been a newtype wrapping `i32` instead of an alias, and there should have been both borrowed and owned versions of it (where the owned one would close the handle on drop). But now we have to live with `RawFd` being the way it is in the stdlib.

The `impl Evented for RawFd` would automatically target unix only ( `RawFd` doesn't even exist on Windows). I'm not sure whether Windows would have a `impl Evented for RawHandle` instead.

But I don't mind the `register_opt` version either. Whatever floats the boat :-)

**Comment by diwic** [comment]
JFTR, I suppose the following would work, right?

    let mioio = mio::Io::from_raw_fd(fd);
    eloop.register(&mioio, mio::Token(i)).unwrap();
    mem::forget(mioio);

**Comment by dimbleby** [comment]
Yeah, what @dwic said.  In particular, everything `RawFd` is unix-only, so I'm not sure what you're saying about windows.

I'm not especially attached to having `Evented` for `RawFd`.  The code in the previous comment works fine (and is what I'm currently doing in my project).  My only objections to it are:

- that `mem::forget` is awkward
- the conversation above leaves me confused as to whether or not `mio::Io::from_raw_fd` is intended to be a public interface

So anything that resolves those two is just fine by me.  

Even just implementing `IntoRawFd` for `Io` would be an advance (when that trait hits stable Rust) so that we can do that in preference to `mem::forget`.

**Comment by alexcrichton** [comment]
I've talked with @carllerche briefly about the cross platform story of mio, and it sounds like in general he wants it to be roughly the same as the standard library which is to say that everything is by default "mostly cross platform" and then authors have to opt-in to platform-specific functionality like this.

The hazard with a direct impl of `Evented for RawFd` is that you can silently (without any indication of an opt-in) rely on that behavior on Unix, which then causes code to fail to compile on Windows. A `register_raw` function in a `unix` module (as @carllerche mentioned) would require a platform-specific opt-in to be acknowledged and make it clear when you're doing something that's unix-specific.

**Comment by carllerche** [comment]
I believe that Rust's policy is to not implement traits on `RawFd`, so we should probably follow that policy.

So, the easiest option here seems to be an `mio::unix::EventLoopExt` trait w/ `register_raw(&mut self, io: RawFd, token: Token, interest: EventSet, opt: PollOpt) -> io::Result<()>` defined on it.

**Comment by dimbleby** [comment]
Or, implement a `mio::unix::BorrowedFd` (feel free to improve the name) which:
- is a newtype wrapper around `RawFd` (or maybe around a `&RawFd`, making even more explicit that it does not have ownership)
- implements `Evented`
- does not close the file descriptor on being dropped
- is as opt-in and unix-specific as you like

Then users can write code very much as we do today, but don't have to `mem::forget` anything once we're done.

**Comment by arthurprs** [comment]
The above looks reasonable to me.

**Comment by rrichardson** [comment]
+1 for UnownedFd

**Comment by diwic** [comment]
:+1: for UnownedFd

**Comment by carllerche** [comment]
Alright, I will accept this strategy. Some bike shedding before I merge:

* I prefer `EventedFd`, while I understand the logic, `UnownedFd` doesn't feel right to me.
* I think a tuple struct w/ a pub field would be better here: `EventedFd(pub RawFd)`
* I would also be open to it being `EventedFd<'a>(pub &'a RawFd)`

**Comment by dimbleby** [comment]
1. Fine
2. Fine (though I'd be intrigued to hear why you prefer a tuple struct; it all seems much of a muchness to me)
3. Yeah, I was in two minds about this.  I think that since we're changing the name I'd also be inclined to switch to using a reference - so that it's still obvious that the `EventedFd` makes no ownership claim

So I propose to make all three changes.

But it'll likely be a day or two before I get around to it.  If you or any of the other commenters are keen to move faster than that: I shan't be in the least offended if my pull request is usurped.

**Comment by diwic** [comment]
Hence the new usage will become:

    eloop.register(&mio::unix::EventedFd(&fd), mio::Token(i)).unwrap();

Works for me.

**Comment by carllerche** [comment]
@dimbleby the tulle struct proposal is to allow more compact usage as @diwic shows above.

**Comment by dimbleby** [comment]
I've now pushed those changes and so hopefully #237 is now ready for merging

**Comment by carllerche** [comment]
Fixed by #237

**Comment by diwic** [comment]
\o/
