### ISSUE TITLE
windows: TcpStream writes should be buffered

### ISSUE THREAD

**Issue by alexcrichton** [carllerche/mio#244]
I have a feeling the Linux kernel does some form of buffering writes to a TCP stream before sending it off to the network. Right now Windows does 0 buffering, and this is quite a big performance hit!

Should investigate what Linux does and probably do something similar to that on Windows

**Comment by briansmith** [comment]
Isn't this a little out of scope of mio? The goal here is to be zero-overhead, but buffers are overhead. Many applications already buffer data internally before writing to the TCP stream, and double-buffering should be avoided.

Maybe it is better to go the other way, and disable the buffering on other platforms.

**Comment by alexcrichton** [comment]
Ah yeah sorry, to be clear there is no buffering or anything on the Unix side of things, this is *only* for Windows. Unfortunately mio's API is basically impossible to translate to a zero-overhead abstraction on Windows (due to the difference of IOCP vs epoll), so we've already bought into some form of overhead on Windows.

What I'm specifically thinking of here is something like:

* When the first call to `write` is seen, the contents are transferred to an owned buffer to submit to the kernel (transfer is required for memory safety)
* While that write is in flight, future calls to `write` will buffer in *another* owned buffer by the TCP handle.
  * Once this second buffer is full, future writes return WouldBlock
* When the first write finishes, the pending write is automatically scheduled.

I'm not 100% sure if this is a great idea, I'd want to benchmark regardless. I noticed that the `test_battery` test in this repo was super slow on Windows, and I suspect that this is the cause (e.g. an architectural difference from Unix), but I'm not 100% sure (just an idea)

**Comment by carllerche** [comment]
@alexcrichton further, it seems like the windows IOCP abstraction is impossible to implement safely in rust w/ zero cost.

The best way to think about what we are doing on windows is implement what Linux does in the kernel for epoll in mio (for windows).

**Comment by briansmith** [comment]
I think maybe we're talking past each other a little bit.

The thing I want to avoid is where the application has a buffer (Vec<u8> or whatever) that mio then copies into a new buffer that mio allocates. Instead, I'd rather have the application transfer ownership of its buffer to mio so that mio can use it without copying and without any additional allocation. This is what I mean by avoiding double-buffering.

Alternatively, and perhaps even more ideally, when sending data, mio should provide a way for the application to grow mio's write buffer by N bytes and access it as a `mut &[u8]` for it to copy its data into, so that it can avoid allocating its own buffer. I would be happy if this interface were a Windows-specific optimization that only works for applications that are willing to add a Windows-specific code path.

The lack of double-buffering is one of the main advantages of the IOCP design so it would be a shame to lose it.

**Comment by rrichardson** [comment]
Is TCP_NODELAY set by default on Windows IOCP?  Nagling might help, here,
but it should definitely be optional.

It is pretty safe to say that in Linux, sockets do not buffer other than in
the outbound socket buffer that is DMA'd to the nic itself, the driver then
rings the doorbell if the nic isn't already working.  It is important to
note that there should be nothing stopping a process from writing into the
nic while its working. This is probably expected behavior, in fact.

Caveat: this is all a bit driver specific on both Linux and Windows, but I
can't imagine that Windows is much different.

Having said that...  I don't think adding another buffer would help with
anything other than very short-term latency (from the local app's
perspective).  If the battery test can't flush out of its own buffering
system (the backlog) fast enough, adding another buffer in the middle isn't
going to help at all.

In the worst case, another buffer would really mess up the behavior
characteristics:  After a single write() call, the OS will usually issue a
PSH, notifying the other side that it needs to flush its buffer back into
the final buffer to be read by read().  If you add an internal buffer, it
would lump the individual write()s into a single write(), thus eliminating
those PSH's that the application developer might be expecting.

This would be annoying for HTTP products.  It would be a show-stopper for
game devs or low-latency financial software.

**Comment by alexcrichton** [comment]
@briansmith yeah I agree that transferring ownership of a buffer into mio would be best for IOCP on Windows, but the current goal of mio is to optimize for Unix and then implement the same interface on Windows. As a result the traits take `&[u8]` and `&mut [u8]` buffers, so mio's forced by design to at least allocate *a* buffer when a write is scheduled.

I'm quite interested in exploring the space of I/O optimized for both Windows and Unix in theory, perhaps with an interface like you're mentioning, taking a buffer by value. This kind of library would probably use mio to be implemented on unixes, and then Windows would perhaps have a custom implementation with a direct binding to IOCP (to avoid the overhead of mio on Windows).

---

@rrichardson yeah I agree that doing extra buffering here would certainly be quite tricky, and we'd have to be careful to not mess with the semantics of normal reads/writes (which I'm certainly not comfortable enough to say so on myself). 


I've done some profiling on Windows now and I no longer think that this is super pressing, and there's been some good points brought up here, so I'm going to close as "not now".
