### ISSUE TITLE
what about sctp

### ISSUE THREAD

**Issue by iqualfragile** [carllerche/mio#318]
Too different to make it work? too little interest? just not a priority right now?

**Comment by rrichardson** [comment]
I think it would be great to have. On OS's for which there is kernel
support,  you can register raw file descriptors, so you should be able to
register your sctp sockets for read/write events, there just wouldn't be
any support for sctp streams in the API.

To support that, we would need sctp socket options enums in nix-rust.  Pull
requests accepted.

It seems unlikely that sctp would be supported on any systems where it
doesn't use the default posix socket interface, that would be a lot of
work.

**Comment by carllerche** [comment]
I'm going to close this for now.

Mio currently supports the ability to create custom `Evented` types. This is ideally enough to implement the requested feature in a separate library. If it is not, then a new issue should be opened to figure out what is missing in order to support sctp in a third party crate.
