### ISSUE TITLE
Keep reporting "socket already registered" on OS X and Windows

### ISSUE THREAD

**Issue by zonyitoo** [carllerche/mio#327]
Kqueue on OS X does not require explicitly deregister the fd when using `EV_ONESHOT`. But I saw the code in [[1]](https://github.com/carllerche/mio/blob/010445b53baced885b535320515896fb5c9f89a0/src/sys/unix/tcp.rs#L117) called the `associate_selector` and set the `self.selector_id`. After that, all calls will fail because I can't find any code that will reset the `self.selector_id` except `deregister`.

For Windows, even I called `EventLoop::deregister` before I called `EventLoop::register`, it still reported "socket already registered". As I saw in [[2]](https://github.com/carllerche/mio/blob/master/src/sys/windows/selector.rs#L304), it seems that someone have forgotten to reset the `self.selector`, so the check in here [[3]](https://github.com/carllerche/mio/blob/master/src/sys/windows/selector.rs#L257) will always fail.

**Comment by carllerche** [comment]
Unfortunately, this is expected behavior. With IOCP, a socket is associated with an IOCP handle for the lifetime of the socket, even if you call deregister. Since Mio's socket definitions are meant to be portable, we must simulate this behavior on *nix platforms.

If you want to bypass this behavior, you can by using *nix specific extensions in Mio, specifically `EventedFd` with `std::net` socket types.

**Comment by zonyitoo** [comment]
What I wanted to do is

1. Register the IO object into the event loop when I got `WouldBlock` error.

2. If I got notified from the event loop, I will deregister the IO object from the event loop so that I can register it again in condition 1.

How to implement this behavior with the latest Mio 0.5 version?

**Comment by rrichardson** [comment]
Perhaps just leave it registered all the time, but check the event type in
your callback and ignore it if your state machine says to do so.

**Comment by carllerche** [comment]
@zonyitoo this should be possible w/ Mio 0.5. You simply can't register it w/ a *different* `EventLoop`. I can look again, I haven't seen an issue w/ deregistering & registering w/ the same `EventLoop`, that should be possible.

**Comment by zonyitoo** [comment]
But yes, I am going to re-register it into a different `EventLoop`. In my coroutine implementation, it is because coroutines got notified will possibly be moved to another worker thread, and each thread has its own `EventLoop`.

If I put the MIO into its own I/O thread, then it will cause too many inter-thread communications, I don't think this is a good idea.

**Comment by carllerche** [comment]
Unfortunately, moving a socket between event loops is not possible on windows. If you don't want to support windows, you can make this work by using std::net types with EventedFd, but then no windows support :-(

How do you decide if a coroutine gets moved to another thread? Can you make your scheduler aware of affinity constraints?

**Comment by zonyitoo** [comment]
@carllerche Those starving worker threads will try to steal works from the busy one, then a coroutine will be moved from one thread to another. When it calls I/O functions, the IO object will be registered on the event loop on that thread.

So it is hard to restrict the IO object to re-register into the original event loop.

I want Windows support. So it would be better to find a solution for this issue.

**Comment by carllerche** [comment]
You could use the same event loop from multiple threads (polling from multiple threads) but I am not sure that is better.

**Comment by zonyitoo** [comment]
Then all worker threads will need to synchronize with the I/O thread, and also, coroutines should be waked up in the original thread that they are running for making good use of CPU cache.

If this is the only option to bypass the "socket already registered" error both on Unix and Windows, I should make a benchmark for them. But I still hope to use one-loop-per-thread strategy.

**Comment by lhecker** [comment]
@carllerche @alexcrichton I think you could use the [`FileReplaceCompletionInformation` API](https://msdn.microsoft.com/en-us/library/windows/hardware/ff728840.aspx#FileReplaceCompletionInformation) on Windows 8.1+.

If I'm correct: Would you consider adding or merging this (or maybe creating a seperate issue for this)? Because I could only imagine that this could be quite useful for performance sensitive applications in the future when more and more users upgrade to Windows 8 and higher...

**Comment by alexcrichton** [comment]
@zonyitoo for a Windows implementation of migrating coroutines one-event-loop-per-thread architecturally not be the right choice at that layer. The mio model is that at most one thread waits on an event loop at any given point in time, but Windows completion ports explicitly support many threads waiting on one port.

It may be possible for mio to support platform-specific extensions to support this model, but I suspect that's the way that you'd ideally support something like this.

**Comment by alexcrichton** [comment]
@lhecker that also seems plausible, yeah! I haven't had a chance to try it out at all, though.

**Comment by zonyitoo** [comment]
@alexcrichton Right now we have already migrated to I/O threads + worker threads model. But the problem is right now we have to use a Mio's channel to register events and use another channels to notify events to worker threads, which has huge performance drawback (when the application is doing a lot of I/O operations). What's your suggestion?

**Comment by alexcrichton** [comment]
So in theory, from a high level, a Windows implementation of coroutines would have one completion port which a bunch of threads work on. That one completion port would be *the* completion port for all I/O handles created by the application. Whenever a thread doesn't have any work to do, it'll wait for a completion to happen, at which point it'll context switch to the coroutine which issued the I/O and then it'll keep going. This means that during any call to I/O you may switch threads (e.g. submit the work on thread A and run the completion on thread B).

This strategy is "kinda" one event loop per application and many threads share that event loop, but it's not the model that mio is currently exposing (it'd essentially require `&self` borrows everywhere instead of `&mut self`).

So that's kinda in general what I would expect the *ideal* architecture to look like, but mio currently doesn't lend itself well to such an architecture unfortunately. This solves the "migrating between event loops" problem by just sidestepping it completely (there is no migration).

I'm not sure if @lhecker's mentioned API would work, it may though! Not sure if there's cost associated with moving threads between completion ports. It may also be hard to find a point where there's guaranteed to be no I/O on one port maybe?

**Comment by zonyitoo** [comment]
I am not sure I have got your point. What you mean is

1. If I have thread A, B and C, when some of my threads does not have work to do, then they could all call `EventLoop::run` on the same `EventLoop` instance to wait for events? And then the `EventLoop` could tell each of them which of their registered events are happened. Or

2. If I have thread A, B and C, A is the I/O thread, which will always try to block on `EventLoop::run` and responsible to dispatch events to workers (B and C). When B and C want to do I/O, they will register it to the `EventLoop` which is controlled by A and then do anything else until getting notified by A.

The 2. is the model that I am currently using. If I am wrong, I may have to read the document about IOCP.

**Comment by alexcrichton** [comment]
Ah yes what I mean is more along the lines of (1). There'd only be one `EventLoop` (assuming there's a one-to-one correspondance between event loops and completion ports), and all threads should share this event loop.

The Rust API to IOCP that mio uses is [the `miow` crate](http://alexcrichton.com/miow/miow/index.html) and browsing around that may give you a good idea for how IOCP works, although the official Windows docs would also certainly suffice for that!

**Comment by zonyitoo** [comment]
The (1) model can be used right now? If I do

```rust
let mut shared_event_loop = EventLoop::new();

for _ in ..4 {
    // Creates 4 threads and they will call run_once on the same EventLoop with different Handler
    thread::spawn(|| {
        let mut local_handler = MyHandler::new();
        shared_event_loop.run_once(&mut local_handler, None);
    });
}
```

And each of the threads can register events simultaneously. Is this model really work with `epoll` and `kqueue`?

**Comment by zonyitoo** [comment]
Another problem is: Why the `run_once`, `register` and `deregister` require `&mut self`? Is it safe to share it between threads with mutable reference? I saw the `EventLoop` has implemented `Sync`.

**Comment by alexcrichton** [comment]
Yeah that's basically what I'm saying "in theory works". Under the hoodl epoll/IOCP/kqueue all support that (as they have to be safe to call from many threads anyway). In terms of a Rust API that's not really supported because of the `&mut self` requirement, but I was talking with @carllerche a bit today about how that requirement could perhaps be relaxed.

I suspect that the `Poll` API at least can do away with `&mut` entirely, but the `EventLoop` has some other internal state which may require single-threaded mutation. Regardless though if coroutines were to use `Poll` directly that may be what you want in the long run anyway.

**Comment by zonyitoo** [comment]
What is actually bothering me is that how to wake up the Coroutines that are blocked by I/O events. I am now store the `Handle` to a Coroutine into a `Slab` to make it possible for the `Handler` to wake up a specific Coroutine. But because the `Slab` is going to be shared between threads, so I have to lock it with a `Mutex`. Which means that ...

```rust
let event_loop = EventLoop::new(); // EventLoop in global
// IoHandler in global. The IoHandler impls Handle and it stores those blocked
// coroutines.
let io_handler = Mutex::new(IoHandler::new());

fn io_thread() {

    loop {
        let mut io_handler = io_handler.lock().unwrap();
        event_loop.run_once(&mut io_handler, Some(100)).unwrap();
    }
    
}

fn wait_event(coro: Coroutine, fd: &Evented) {

    // This function will be called after the `coro` is blocked and return to the
    // context of the worker thread

    let mut io_handler = io_handler.lock().unwrap();
    let token = io_handler.make_token(coro);
    event_loop.register(fd, event_set, token, Edge).unwrap();

}
```

So as you can see, because the `io_handler` cannot be `Sync`, so `register`ing and `run_once` cannot actually run simultaneously.

Here is another experiment I did:

```rust
let event_loop = EventLoop::new(); // EventLoop in global

fn io_thread() {
    let mut local_handler = IoHandler::new();

    loop {
        event_loop.run_once(&mut local_handler, Some(100)).unwrap();

        // When the event happens, the IoHandler will simply transmute the Token
        // back to Box<Coroutine> and wake him up.
    }
    
}

fn wait_event(coro: Box<Coroutine>, fd: &Evented) {

    // This function will be called after the `coro` is blocked and return to the
    // context of the worker thread

    // Force to transmute a raw pointer to a Coroutine as the Token
    let token = Token(Box::into_raw(coro) as usize);
    event_loop.register(fd, event_set, token, Edge).unwrap();
}
```

In this model, If you `Ctrl+C` kill the program, which is running a server with acceptor and a bunch of connected `TcpStream`s. And you won't be able to start the program again because of error: `Address already in use (os error 48)`.

I don't know why if I store the `Coroutine` in `Slab` will work for `Ctrl+C` but it is not working after setting the raw pointer into the event loop.

**Comment by zonyitoo** [comment]
I notice that Rust won't help me to unwind Coroutine's own stack .. So please ignore the previous comment.

**Comment by alexcrichton** [comment]
Yeah there'd in theory be some level of opt-in synchronization if necessary, but again this is all just an idea not sure if it would actually work out
