### ISSUE TITLE
Assign an ID for IOCP on windows

### ISSUE THREAD

**Issue by zonyitoo** [carllerche/mio#334]
I still got stuck with the "socket already registered" error on Windows.

I have already refactored my library to use one single `EventLoop` so that the socket object won't move from one `EventLoop` to another. But I still got "socket already registered" error on Windows. The log on AppVeyor is [here](https://ci.appveyor.com/project/zonyitoo/coio-rs/build/1.0.63).

I was hoping if [this line](https://github.com/carllerche/mio/blob/7b73ce83d12d01a09d1d0d67102f071d1ea2f9dd/src/sys/windows/selector.rs#L258) could add some checking just like the implementation on `unix`, which would check the ID of the `Selector` before reporting this "socket already registered" error.

**Comment by carllerche** [comment]
Good point.

**Comment by GGist** [comment]
I got bit by this bug recently, has there been any progress on it?

In my case the bug happens when I create a ```TcpStream``` that is initially not registered. I then clone that ```TcpStream``` and go to the initial one and call register on that. However, at this point I am unable to either call ```register``` or ```reregister``` on the second ```TcpStream```.

If I try to simply ```register``` the second TcpStream, I hit [this line in miow](https://github.com/alexcrichton/miow/blob/master/src/iocp.rs#L42) and the last OS error is error code 87 "The parameter is incorrect". I am guessing that is because we are trying to register the same socket that we already registered with our single iocp.

If, however, I try to ```reregister``` the second TcpStream, I hit [this line in mio](https://github.com/carllerche/mio/blob/master/src/sys/windows/selector.rs#L375) because when we clone a ```TcpStream``` we don't copy the ```Registration```.

Although in my case, copying the ```Registration``` wouldn't even be enough because I registered the first ```TcpStream``` after cloning it. So really, we need to make sure all ```TcpStream```s have ```Registration```s that are in sync.

Is it as simple as modifying the Windows ```TcpStream``` to hold ```Arc<Mutex<Registration>>``` or are you planning something different? If you have a general idea for what you are wanting to do, and perhaps are open to making a ```0.5.2``` with this fix, I would love to help out!

**Comment by GGist** [comment]
Apologies, I am still familiarizing myself with the code a little bit more.

It looks like you are already doing some locking internally in the ```StreamIo``` structure so that io completions can continue to run even if a ```TcpStream``` was dropped?

Is there any problem with just doing a clone on the ```StreamImp.inner``` when cloning a ```TcpStream``` and instead of implementing ```Drop``` for ```TcpStream```, implement it for ```StreamIo``` so when the ```FromRawArc``` loses all references, the ```StreamIo``` ```Drop``` will kick in?

**Comment by alexcrichton** [comment]
@GGist oh sorry, I forgot to respond! The modification here can probably happen to `TcpStream` and the other I/O objects directly, rather than dealing with their internals that are handling all the I/O. The id should be accessible from the register/reregister/deregister calls at that point.
