### ISSUE TITLE
UdpSocket: Sync On Windows, !Sync On Unix

### ISSUE THREAD

**Issue by GGist** [carllerche/mio#370]
I am not sure if this has been brought up before as I couldn't find anything in the issue tracker, so apologies if this is a duplicate. The only thing I found was [this](https://github.com/carllerche/mio/issues/292) which looks like sharing ```Overlapped``` on Windows was added explicitly.

It seems that on Windows, mio's ```UdpSocket``` is safe to share between threads, however, on Unix platforms, [this is not the case](https://github.com/carllerche/mio/blob/master/src/sys/unix/udp.rs#L11) and a compile error is generated.

I am not sure if the lack of ``Sync`` is due to differences between iocp and epoll, but it would be nice to be able to shared a single ```UdpSocket``` between multiple threads on both platforms.

**Comment by rrichardson** [comment]
This was a design decision.  Technically speaking two threads shouldn't access an fd at exactly the same time, as the results are undefined, so it needs to be wrapped in something that would Marshall access. The API design forces this. 

As far as Windows goes, I think the implementation required that the descriptor be shared among multiple threads, and I *think* it is thread safe. 

I'm investigating whether its time to just migrate all of Mio's net types over to Rust since their net stdlib should have all of the appropriate support now.  Afaict,  Rust's UdpSocket isn't sync either. 

https://doc.rust-lang.org/nightly/std/net/struct.SocketAddrV6.html

I'm going to label this as wontfix, but I'm open to hearing more compelling reasons why we should allow it.

**Comment by GGist** [comment]
I believe Rust's ```UdpSocket``` is indeed thread safe. This compiles and runs fine:

```
use std::thread::{self};
use std::net::{UdpSocket};
use std::sync::{Arc};
use std::time::{Duration};

fn main() {
    let sock = Arc::new(UdpSocket::bind("127.0.0.1:0").unwrap());
    
    let sock_clone = sock.clone();
    thread::spawn(move || {
        println!("{:?}", sock_clone.local_addr());
    });
    
    println!("{:?}", sock.local_addr());
    thread::sleep(Duration::from_millis(500));
}
```

So if you guys are planning on making the switch, you may get this for free.

**Comment by alexcrichton** [comment]
@rrichardson I believe that this was just accidental and hasn't been updated since then, I very intentionally made all of the windows types `Sync` as this allows having something like `Arc<TcpSocket>` which can often be quite useful.

As @GGist points out the underlying OS networking types are safe to use across multiple threads, including reads and writes. You'll probably get nonsensical results if you write concurrently or read concurrently, but reading *and* writing concurrently is generally an expected operation (e.g. one thread reading, another writing).

I also don't think mio can move to vanilla libstd networking types because on Windows at least there must be a layer (lots of shenanigans there) and to have a cross platform API that means there needs to be a layer on Unix as well.

**Comment by rrichardson** [comment]
Yea. I just looked at the shenanigans. We're not getting clear of those any time soon. I think that we could at least fulfill the interfaces with the std::net on Unix, which would cut down on some of the duplicated functionality, but that's an issue for a separate ticket. 

I agree that the underlying file descriptor can and should be usable across threads, after all, it is just an int (on *nix at least).  The UdpSocket, however, has additional mutable state. A cell, which is used as the explicit example of things that shouldn't be Sync. 

From a usability standpoint,  I'm trying to sort out which is better:  Share the UdpSocket or share the underlying fd.  I'm leaning towards the FD, because the additional state in UdpSocket is the selector_id, which associates it with a poller.  If two threads want to poll the same fd with their own epoll's this is acceptable, but for them to do it on the same UdpSocket is nonsensical in the current implementation.

**Comment by alexcrichton** [comment]
The UDP/TCP implementation on Unix have a selector id associated with them to exhibit the same semantics as found on Windows which is that a socket can be associated with at most one event loop. (this can be worked around with `EventedFd`, however). The `Cell` that is currently used to implement it can be trivially replaced with `AtomicUsize`, however, so there's no fundamental need for `!Sync`

**Comment by rrichardson** [comment]
Since the selector_id is used in a very opaque way, I guess it wouldn't be the end of the world to use an atomic and a sentinel value in place of the Option<>

We need to keep parity with the windows API, and since it doesn't have the notion of a file descriptor,  a Udp/TcpSocket object will have to do.  

I still have some concerns, though, reading/writing a socket from multiple threads is certainly something that we should support.  But what about polling?  Polling the same fd from multiple event dispatchers is a technique employed with epoll.  (Not sure about the others APIs)   The current implementation of the *Socket objects would not support that, and one would have to clone the object (or the underlying fd) so it would be pointless to make the object Sync, and one would just duplicate it or the underlying fd instead.

**Comment by carllerche** [comment]
The fix is on `dev` waiting for CI to pass.
