### ISSUE TITLE
UdpSocket::{send_to, recv_from} use None == WouldBlock

### ISSUE THREAD

**Issue by alexcrichton** [carllerche/mio#461]
I forgot to address these in https://github.com/carllerche/mio/pull/459 :(

To align with std, however, they should return `io::Result<T>`  instead of `io::Result<Option<T>>`. This should probably get delayed until the next release of mio.

**Comment by alexcrichton** [comment]
er, next *major* release

**Comment by przygienda** [comment]
So that's more of a question I'm debugging here (fairly frustrating). 

I'm running stock UDP sockets on OSX and just do Redable on edge (or level, same result). As long the load is light, e'thing works like a complete charm. As soon I start to load those sockets (I have couple hundred threads each with a socket and they can pump 30-40 packets per sec each) I get the edge, try to drain, get the Ok(none) [mostly one packet per edge, very, very seldom two] and loose TONS of packets. The kernel says it doesn't loose anything (I pumped up all buffers to crazy sizes by now) so it must be either 

a) mio is missing edges _or_ 
b) mio is giving edge and drains all packets but returns only one 

writing a test here and will drop in later ...

**Comment by alexcrichton** [comment]
Done in https://github.com/carllerche/mio/pull/574

**Comment by carllerche** [comment]
Were you assuming that Ok(None) means no more packets? It actually means
"would block" and try again when you get another notification.

The linked pr deprecated that API in favor of an io error would block

**Comment by neuronsguy** [comment]
Hi, sorry this is too late but could you comment on why this change happened?  

The old API that returned None (or something other than Err for WouldBlock) was substantially more useful for async code.  Now every call needs to be wrapped in a match that looks for the WouldBlock kind rather than having the API cleanly do it.

**Comment by carllerche** [comment]
The goal of Mio is to get it down to a minimal API set that matches `std` as close as possible and to punt API exploration to higher level libs (like Tokio).

The change was done in a patch release because it was not breaking. The old API is still there but marked as deprecated. The old API will stay there until 0.7 is released. You can update any code to the new mio API at your leisure.

**Comment by neuronsguy** [comment]
I believe the change was in fact breaking: UdpSocket send_to and recv_from changed their type signatures which breaks downstream code.

That said, if I understand correctly, you are trying to remove non essential differences between mio and stdlib API, and special casing WouldBlock seems nonessential because it can be done by the client?

While I disagree with the goal, the change makes sense in light of it.  In any case, thank you very much for the explanation, and the thought and effort you've put into this excellent crate!

**Comment by carllerche** [comment]
Again, it is not breaking because no change to **existing** types were made. A brand new `UdpSocket` type was added in a different module. As such, all existing downstream code will continue to work fine. If a breaking change was added during a patch release, it is a bug.
