### ISSUE TITLE
Kuddos: Could we have HIGH/LO PRIO timers & events 

### ISSUE THREAD

**Issue by przygienda** [carllerche/mio#479]
OK, fantastic work here. Point. 

Request (coming from long experience on massively scaled up systems): Can we have low-priority & high priority timers & registrations. All such "scheduler" based systems become limited under heavy load and the solution is to have high-priority & low priority events & timers to allow gracefull load-shedding, e.g. dropping a connection and loosing lots of state synchronization is _much_ worse than e.g. delaying some low-background-computation. 

i'm willing to contribute albeit I'm only a month or two into Rust (couple KLOCs of code) heavily so I may be overwhelmed ;-)

**Comment by tailhook** [comment]
Why not just use a thread for low-priority tasks and use thread priorities?

**Comment by carllerche** [comment]
@przygienda Could you elaborate some on how such a feature would work sockets directly on epoll? 

Re timers: probably since I'm going to remove timers from Mio proper and be moved into another crate, however Mio should provide the building blocks for third party libs to build what they need in a way that can integrate w/ the system selector (epoll, kqueue, iocp, etc...)

Does that make sense?

**Comment by carllerche** [comment]
Closing for now. Feel free to reopen / open a new issue if there is further discussion needed.

**Comment by przygienda** [comment]
I think in the new MIO code that can be resolved by having two builders and registering them indepencently & just process diff # of those per event queue run or something. Didn't get to that stuff yet ...
