### ISSUE TITLE
EventedFd for Windows

### ISSUE THREAD

**Issue by mxre** [carllerche/mio#514]
I'm in the process of writing a program with the curl (with the curl-rust bindings) multi API. This API provides the caller with a curl_socket_t (which for Unix systems is a socket fd, and for Windows a SOCKET handle).

In Linux it is then possible to create an EventedFd from the provided socket fd from an already open socket.

But for windows systems the seem to be no API in MIO to create an Evented TcpStream from a Windows SOCKET handle (from an already open socket). As far as I can see this does not seem to be trivial to implement.

**Comment by alexcrichton** [comment]
Thanks for the report! It's currently not possible to have an `EventedFd` on Windows due to the way mio works on Windows (IOCP). Similarly it's not possible to use IOCP along with the multi support in libcurl. If you'd like to see an example of how to do so in a separate thread though then you can take a look at https://github.com/tokio-rs/tokio-curl.
