### ISSUE TITLE
unresolved import `libc::EPOLLONESHOT` on the android platform

### ISSUE THREAD

**Issue by MarginGitHub** [carllerche/mio#568]
When I use tokio crate on the Android platform, the compiler gave me an error (mio crate throws the error):
```rust
use libc::{EPOLLERR, EPOLLHUP, EPOLLRDHUP, EPOLLONESHOT};
```
no `EPOLLRDHUP` in the root. Did you mean to use `EPOLLHUP`?
error[E0432]: unresolved import `libc::EPOLLONESHOT`

**Comment by gdf8gdn8** [comment]
epoll EPOLLONESHOT is implemented since linux kernel 2.6.2, but on android platform EPOLLONESHOT is missing in rust libc. 

Should be an bug in rust libc implementation.

see [http://man7.org/linux/man-pages/man2/epoll_ctl.2.html](http://man7.org/linux/man-pages/man2/epoll_ctl.2.html)
see [https://doc.rust-lang.org/libc/arm-linux-androideabi/libc/index.html?search=EPOLLONESHOT](https://doc.rust-lang.org/libc/arm-linux-androideabi/libc/index.html?search=EPOLLONESHOT)

What I'm missing is EPOLLWAKEUP and EPOLLEXCLUSIVE for mio implementation.
EPOLLWAKEUP (since kernel 3.5) and EPOLLEXCLUSIVE (since kernel 4.5) could be bring up several issues on compiling for older systems.

**Comment by MarginGitHub** [comment]
@gdf8gdn8 So how to fix this bug, or just wait?

**Comment by gdf8gdn8** [comment]
I think this is an bug in libc, but the workaround for mio can be to remove EPOLLONESHOT when build for android till libc bug is fixed.
So this is an issue for mio.

I created an issue on this missing feature in rust libc repository.
see [https://github.com/rust-lang/libc/issues/548](https://github.com/rust-lang/libc/issues/548)

**Comment by MarginGitHub** [comment]
@gdf8gdn8 Okay, thank you! Look forward to good news

**Comment by carllerche** [comment]
Thanks for the report. This is indeed an issue with the libc crate. However, this is also handled on master. I would try using master form now. A release should be coming soon.
