### ISSUE TITLE
Implement Index<usize> for Events

### ISSUE THREAD

**Issue by dtolnay** [carllerche/mio#681]
The mio::Events type looks a lot like Vec - it has a function get(usize) -> Option\<Event\> which returns None if the index is out of bounds, and it has IntoIterator. It would be convenient to implement Index to enable square-bracket indexing that panics on out of bounds.

```rust
println!("{:?}", events[0]);
```

**Comment by ahmedcharles** [comment]
This isn't trivial. The epoll implementation of `Events` doesn't store `Event` instances directly, it stores `libc::epoll-event` instances. This is why `get(usize)` returns `Option<Event>` rather than `Option<&Event>`. `Index` requires `&Event`, which can't be a temporary, because it doesn't live long enough.

**Comment by alexcrichton** [comment]
Ah yes this isn't implementable easily and intentionally so, we often perform translations on the returned events from the system to coalesce and/or generate more mio events.

**Comment by carllerche** [comment]
Actually I'm pretty sure we wanted to deprecate indexed access in favor of an iterator only API.

**Comment by dtolnay** [comment]
I filed #697 to follow up if necessary.
