### ISSUE TITLE
Can't get `poll.poll` to block - loop is just spinning

### ISSUE THREAD

**Issue by jonathanstrong** [carllerche/mio#828]
I have tried a variety of ways to get calls to `Poll::poll` to actually block to no avail.

All of my attempts are to listen and send with `UdpSocket`. I'm using linux (ubuntu 16.04) with xeon cpus, and tried several different machines. Using mio v0.6 (`mio = "0.6"` in Cargo.toml).

If I run the [example code](https://carllerche.github.io/mio/mio/net/struct.UdpSocket.html) from the `UdpSocket` docs I get 100% cpu usage (with `println!`s removed, otherwise 20-30%). 

Am I doing something wrong or is this expected behavior? My goal was to block wait on a UDP socket. I want to avoid `thread::sleep` to keep cpu down based on the premise this would increase the latency for responding to incoming packets. In other words, my goal is best latency profile short of busy spinning.

I just want to know if I'm doing something wrong, and I should be able to achieve this with mio, or if this is not possible. I thought it was, based on the docs, but I can't seem to get it to work. Thanks!

**Comment by hjr3** [comment]
mio is for non-blocking IO, so blocking is usually discouraged outside of the main loop. If you try to block in the linked example, the program would never make any progress. The example program pegs a CPU because it is essentially a loop reading/writing to loopback (in other words: very little I/O).

In a real world scenario, the server is going to be polling the socket. Per the for [Poll::poll](https://carllerche.github.io/mio/mio/struct.Poll.html#method.poll):

> The function will block until either at least one readiness event has been received or timeout has elapsed. A timeout of None means that poll will block until a readiness event has been received.

Using the timeout, you have control over how long you want the blocking behavior to last. This sounds similar to what you were trying to do with `thread::sleep`. 

The reason you are not seeing blocking behavior in the UDP example is that the client is always ready to write and thus that event is firing constantly. If you wanted to simulate slower behavior, you could register the `sender_socket` with `PollOpt::edge() | PollOpt::oneshot()` and then reregister after a certain number of _ticks_ in your loop. To count the ticks, you can have something like `let mut i = 0;` and increment `i` once every time you loop. Then you can do something like `i % 10`. Here is a working [example](https://gist.github.com/rust-play/7b264ec589f0409b8beca187bb5aee58).

**Comment by carllerche** [comment]
I ran the example and don't get 100% CPU (on both os x & linux). Do you have a repro?

**Comment by carllerche** [comment]
@hjr3 

> The reason you are not seeing blocking behavior in the UDP example is that the client is always ready to write and thus that event is firing constantly.

This *should* not be the case w/ edge triggered notifications. Only level. The example uses edge.

**Comment by jonathanstrong** [comment]
sorry guys, I realized my mistake just now, and it's really dumb. 

my event loop is not using the cpu. But in `main`, where I set it up, I kept the program alive this way: 

```
fn main() {
    let thread = listen_udp();
    loop {}
}
```
The `loop {}` is the source of all my problems. Everything working correctly now.

**Comment by carllerche** [comment]
np!
