### ISSUE TITLE
Fix CI

### ISSUE THREAD

**Issue by carllerche** [carllerche/mio#863]
iOS CI is no longer working. I am not sure why.

If it can be fixed, then it should be fixed. Otherwise, we should consider switching to a "compile only" CI mode.

**Comment by hawkw** [comment]
I've done a little testing and it looks like  the `xcrun simctl launch com.rust.unittests`... stage in `deploy_and_run_on_ios_simulator.rs` _is_ actually running for upwards of 20 minutes with no output, so the solution may not be as simple as just using `travis_wait` to bump up the timeout a little. Possibly it's actually hanging.

However, it runs fine on my mac (macOS 10.12.6 (16G1408)) with the iOS 10.2 simulator, so if something's causing it to hang, it may be specific to the CI environment. Will continue digging.

**Comment by hawkw** [comment]
Okay, I'm fairly sure the iOS build on Travis is actually hanging (rather than just slow):
![screen shot 2018-08-15 at 4 12 43 pm](https://user-images.githubusercontent.com/2796466/44178232-435d3f80-a0a6-11e8-9544-265c6dda3202.png)

I haven't yet been able to determine what makes it hang on CI but not locally...
